### ISSUE TITLE
Handling response success vs errors?

### ISSUE THREAD

**Issue by gregblass** [qbwc/qbwc#104]
Just wondering what I would expect the QBWC to return as a response for success vs error?

So in `handle_response(response, ...)`, i'd want to do:

`
if response == 'success'
  do this
else
  do that
end
`

But what will that 'response ==' be?

**Comment by gregblass** [comment]
response["xml_attributes"]["statusSeverity"] == "Error"

**Comment by gregblass** [comment]
Or, response["xml_attributes"]["statusCode"] != "0" (0 is success, anything else is a failure)

**Comment by JasonBarnabe** [comment]
Note that statusCode != 0 for "expected" errors too, like "not found" and such.

**Comment by gregblass** [comment]
Yep, sorry I should have specified - that's why I posted the 2nd comment...it will cover anything but a success. So better that way.

**Comment by gregblass** [comment]
Thanks for your help @JasonBarnabe!!
