### ISSUE TITLE
Rails 5 depreciation warnings: before_filter -> before_action

### ISSUE THREAD

**Issue by gregblass** [qbwc/qbwc#106]
`DEPRECATION WARNING: around_filter is deprecated and will be removed in Rails 5.1. Use around_action instead. (called from block in included at /Users/gregblass/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/qbwc-3c88b26b8a29/lib/qbwc/controller.rb:12)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in included at /Users/gregblass/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/qbwc-3c88b26b8a29/lib/qbwc/controller.rb:12)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in included at /Users/gregblass/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/qbwc-3c88b26b8a29/lib/qbwc/controller.rb:12)
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from block in included at /Users/gregblass/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/qbwc-3c88b26b8a29/lib/qbwc/controller.rb:12)
Processing by QbwcController#qwc as HTML`

**Comment by gregblass** [comment]
False alarm. This is clearly fixed in the latest version already...I must be running an older version.

**Comment by gregblass** [comment]
I just wasn't running off of the master branch. Any reason for the delay in gem release?

**Comment by gregblass** [comment]
Actually this is being caused by the washout gem.

**Comment by gregblass** [comment]
Washout 0.10.0 is the issue. It was fixed in 0.11.0. Dependencies should probably be updated here?

**Comment by JasonBarnabe** [comment]
See #99.

**Comment by gregblass** [comment]
Looks like its merged: https://github.com/inossidabile/wash_out/pull/221

**Comment by gregblass** [comment]
Hmm, actually I can't tell. I think their CI build failed? In any case, I can just specify 0.11.0 in my gemfile.lock for my project just fine. I'm using Rails 5 so I shouldn't have that issue.

**Comment by gregblass** [comment]
Hmm, that won't do the trick. Oh well, I'll have to live with the depreciation warnings for now.

**Comment by gregblass** [comment]
I was able to just fork it and update the dependency in the mean time. Thanks for your help!
