### ISSUE TITLE
'Jobs exist, but no jobs pending for 'C:\company_file.QBW'

### ISSUE THREAD

**Issue by gregblass** [qbwc/qbwc#107]
I'm so close to getting this implementation working, but it looks like I'm not specifying which company file to use with the jobs I'm queueing up:

```
4 jobs exist, checking for pending jobs for company 'C:\Users\Public\Documents\Intuit\QuickBooks\Company Files\company_file.QBW'.
Authentication of user 'derp' succeeded, but no jobs pending for 'C:\Users\Public\Documents\Intuit\QuickBooks\Company Files\company_file.QBW'.
```

I just looked at the docs again and I'm not seeing where I can specify that the jobs are for that company file?

**Comment by gregblass** [comment]
I'm leaving the 3rd parameter as an empty string when calling `QBWC.add_job`

**Comment by gregblass** [comment]
If you specify a company file in the qbwc.rb config, you have to pass it into the add_job method.

**Comment by JasonBarnabe** [comment]
Yes, [it looks like the README is incorrect](https://github.com/qbwc/qbwc/blob/master/lib/qbwc.rb#L99). I will fix.
