### ISSUE TITLE
QBWC Jobs Hang Randomly and post deposits over and over

### ISSUE THREAD

**Issue by gregblass** [qbwc/qbwc#110]
I launched a client onto new software in the beginning of May, and QBWC was working great, until recently (Friday) a qbwc_job got hung up and kept making deposits over and over (infinitely). We were able to do some damage control, but the client had to manually delete over a 100 deposits.

It just happened again a second ago. Luckily we caught it after it did 8 copies of the deposits.

I know this issue could really be caused by a number of things - my code, this library, the desktop machine running the QBWC (or any combination thereof).

I'm posting this as a general question and to open up a dialog here - has anyone seen or heard of this issue before?

**Comment by gregblass** [comment]
It looks like whats happening is that the job gets stuck there forever and doesn't get removed. The 'enabled' boolean stays set to '1'.

**Comment by JasonBarnabe** [comment]
"gets stuck there forever and doesn't get removed" is the default behaviour, see https://github.com/qbwc/qbwc#creating-jobs

So it would depend on the code you have (or don't have!) to make your job stop running.

**Comment by gregblass** [comment]
Really appreciate the response @JasonBarnabe! And good call. Here's my code:

```
def handle_response(response, session, job, request, data)
  if response["xml_attributes"]["statusCode"] == "0"

    # Log the quickbooks post
    quickbooks_post = QuickbooksPost.create(
      invoice_subtotal: data[:invoice_subtotal],
      invoice_pa_sales_tax: data[:invoice_pa_sales_tax],
      invoice_phila_sales_tax: data[:invoice_phila_sales_tax],
      invoice_payments: data[:invoice_payments],
      invoice_prepayments: data[:invoice_prepayments],
      payments: data[:payments],
      prepayments: data[:prepayments]
    )

    Transaction.find(data[:transaction_ids]).each do |transaction|
    
      # Update the transaction
      transaction.update(
        posted_to_quickbooks: true,
        posted_to_quickbooks_on: Date.current,
        quickbooks_post_id: quickbooks_post.id
      )

      # Update the invoice if it is an invoice transaction
      if transaction.invoice
        transaction.invoice.update(
          posted_to_quickbooks: true,
          posted_to_quickbooks_on: Date.current,
          quickbooks_post_id: quickbooks_post.id
        )
      end
    end

    # Delete the job so it doesn't run again
    QBWC.delete_job(job)
  else
    Rollbar.error("#{response["xml_attributes"]}")
  end
end
```

All the stuff in the middle shouldn't affect it I don't think - just ancillary logging I'm doing in the software.

Rollbar isn't reporting any errors, and all of that ancilary stuff seems to be running correctly - that is its creating the quickbooks post class that I have there and updating the transactions. It just seems to fail on the QBWC.delete_job(job) portion...

**Comment by gregblass** [comment]
This code worked the first 71 times it ran, then on #72, didn't delete the job....and then happened on #76 again today.

**Comment by gregblass** [comment]
I was able to find an error in the QBWC log file on the desktop computer! So no issues with this library. Thanks again!
