### ISSUE TITLE
Anyone doing consulting work setting up web connector and writing SOAP endpoint?

### ISSUE THREAD

**Issue by bstumpexb** [qbwc/qbwc#121]
Hello. I have a request for consulting work. 
We have a website that will need to connect with Quickbooks.
Invoices will originate from website.
Bills will originate from website.
Marking Bills and Invoices paid will originate in quickbooks and be viewable on custom website.
Is this page a place to find the right person to work with on this project?

**Comment by ayarulin** [comment]
@bstumpexb i have done integration with QB for real-world project, so can share my experience, feel free to ask me if you have any issues.

**Comment by Norm-RR** [comment]
@ayarulin or any other Developers,
I am a Developer looking for a QBWC SOAP Service for NODE.JS or even better METEOR.
I've done QBWC and SOAP via ColdFusion before, but i am new to NODE architecture and just looking for some code to springboard my development (something to reverse engineer lol)

Any help greatly appreciated!
~N
