### ISSUE TITLE
secret_token in session.rb causing issues

### ISSUE THREAD

**Issue by 56kyle** [qbwc/qbwc#128]
Hi, this is my first time making an issue so I apologize if there is a format to follow that I am not aware of.
I have been running a rails server mockup since I don't have direct access to the site I am integrating with quickbooks. I was to the point where I could create jobs in mysql through qbwc, but qwc would give an authentication error upon manually running update.

In the rails console it would give an error saying that config.secret_token is not a method and suggested putting secret_key_base. After looking into it for a while and trying several things such as 'rake secret'/etc and putting variable in config/initializers I eventually tried changing "qbwc-1.1.0\lib\qbwc\session.rb:21" from 

    @ticket = ticket || Digest::SHA1.hexdigest("#{Rails.application.config.secret_token}#{Time.now.to_i}")

to (only change is secret_token -> secret_key_base)

    @ticket = ticket || Digest::SHA1.hexdigest("#{Rails.application.config.secret_key_base}#{Time.now.to_i}")

I have no idea if this is actually a solution or if I am just making it reference something I put in while trying various ideas. I just figured it might be worth mentioning incase it actually is an issue.

**Comment by JasonBarnabe** [comment]
What version of Rails are you using?

**Comment by 56kyle** [comment]
Rails 6.0.2.1 - also just as an update I haven't ran into any issues since making the change

**Comment by 56kyle** [comment]
After multiple months of working on the same project that relies on qbwc I just for the first time noticed the start to the description of this gem... Sorry about bringing this up as an issue. Although for reference   it seems like just making that change was enough to have the gem working for rails 6; although I haven't ran through tests or anything so I don't know if something else may show up.

**Comment by JasonBarnabe** [comment]
This should be fixed to work with Rails 6.
