### ISSUE TITLE
Adding item to quickbooks is not working

### ISSUE THREAD

**Issue by sakader** [qbwc/qbwc#133]
I have tried to create non inventory item using qbwc gem but it seems not working, I am getting the following error message in QuickBooks Web Connector 2.3.0.36. 
"Quickbooks found an error when parsing the provided XML text stream."
following are the request and the error that I got from rails server log,
![request_log](https://user-images.githubusercontent.com/7814123/75545379-5e0cc480-5a50-11ea-99cf-cfe0f7d81631.png)
![parsing error](https://user-images.githubusercontent.com/7814123/75545388-62d17880-5a50-11ea-8fc1-26cda05236f9.png)

I was able to create customer in same way

**Comment by albertoaa** [comment]
@sakader I'm facing a similar issue but when trying to create a new customer. Since you were able to create a customer, can you provide a sample code on how to create a customer? I'm getting `RuntimeError (/QBXML/QBXMLMsgsRq/Name is not a valid type)`. Thanks in advance

**Comment by sakader** [comment]
Hi @albertoaa I have figured out the solution for my add item issue, it was happening because due to the order of the elements in the xml! I believe you are facing the same issue. Please make sure to provide the elements in the same order as it is mentioned in the documentation when you are sending the request to quickbooks desktop, you may not provide the ones that are optional but whatever you provide (mandatory or optional) make sure you follow the order of those as mentioned in the documentation.
