### ISSUE TITLE
Question About Multiple Users

### ISSUE THREAD

**Issue by bkroeker** [qbwc/qbwc#79]
Hi there! Thanks for releasing this gem; it's been helpful so far.  I do have a question about multiple users though, and I hope you can help me out.

I'm writing a large scale rails app which will handle potentially hundreds of thousands of users.  The app deals with business-related data, and I'm trying to implement the ability for a user to synchronize their data with their QuickBooks Desktop software.

## Scenario:

Bob in Canada has a company named "Bob's Company", and let's say his company file is stored in C:\Quickbooks\mycompany.qbw. He's indicated he wants to keep his vendors synchronized.

Susan is in the US, and has a company named "Susan's Company" stored in C:\Quickbooks\mycompany.qbw (ie. the same location as Bob's, just different machines in different countries).  She wants to keep her invoices synchronized.

## Analysis:

If I understand correctly, the qbwc gem currently only tells companies apart based on their file path.  In the above scenario, there are two different companies with the same file path, making it a non-unique field.  Additionally, my rails app doesn't care what file path the companies are at -- users can use whatever QB companies they want, and I don't want to ask them to enter the path into my website just so I can store it for this purpose unless absolutely necessary.

For the purposes of authentication, I've generated unique QBWC usernames for Bob and Susan's companies, let's say "A1B2C3", and "Z9Y8X7" respectively.  (Additionally, I've also generated passwords for them which I display for them next to their custom "Download QWC file" links.)  Thus, when they authenticate, they will each use credentials which I know to be unique -- no other user of my rails app will have a conflicting username.

So when queueing up jobs, I need to be able to use a unique value (like the QBWC username, or potentially some other unique ID, like, say, the database ID of their respective companies in my postgres database).  So if Bob creates a new vendor in my app, I can queue up my CreateVendor worker for Bob's Company, and if Susan creates a new invoice in my app, I can queue up a CreateInvoice worker for Susan's Company.

## Solution:

If I understand how this gem works correctly, it does not currently support this scenario.  To fix it, I'd have to modify the gem's behaviour, and:

1. add a column to the "qbwc_jobs" table to store the unique company ID
2. modify QBWC.add_job to accept the unique ID instead of the non-unique company file path
3. modify QBWC.pending_jobs and its callers to use and filter on the unique ID instead of the non-unique company file path

Does this all sound correct to you, or am I missing something obvious?

Thanks!

**Comment by JasonBarnabe** [comment]
Unfortunately we're limited here by what QuickBooks Web Connector can do, but I think it's workable for what you want to do. 

> I don't want to ask them to enter the path into my website just so I can store it for this purpose unless absolutely necessary.

The `authenticate` call takes a username and a password and returns the path of the QuickBooks file to access. You can also return an empty string, meaning "whatever's open". So you'll have to choose the lesser of two evils here.

> So when queueing up jobs, I need to be able to use a unique value (like the QBWC username, or potentially some other unique ID, like, say, the database ID of their respective companies in my postgres database).

I very much developed QBWC with my use case in mind - multiple users on a local network accessing a single set of multiple files (each user has the same paths to the same files). I think the simplest solution to also support what you want to do is if we passed the session as a parameter to worker's `requests

**Comment by bkroeker** [comment]
> You can also return an empty string, meaning "whatever's open".

Yup, that's what I'm doing right now, and what I'd like to continue doing.

> I think the simplest solution to also support what you want to do is if we passed the session as a parameter to worker's requests and should_run?, and then you could check session.user to see what you want to do.

This doesn't sound very scalable to me.  If there are 5000 businesses connected to QBWC, each which, say, have 3 CreateResource workers queued up, your solution would fetch (5000 x 3) jobs for each incoming QWBC action request and run each against the should_run? method in ruby to see whether it should be performed or not, no?  Ideally we would filter these in the database, similar to what you do now with the company path, we'd just need to have the database filter on a value unique to the company, and it would need to have a corresponding database index for optimal performance.  This means it would be a very fast database lookup to find (1 x 3) pending jobs -- a total of 3 jobs to process instead of 15000.

My temporary solution has been to overwrite the Controller module's authenticate method to the following:

```ruby
  def authenticate
    username = params[:strUserName]
    password = params[:strPassword]
    if !QBWC.authenticator.nil?
      company_file_path = QBWC.authenticator.call(username, password)
    elsif username == QBWC.username && password == QBWC.password
      company_file_path = QBWC.company_file_path
    else
      company_file_path = nil
    end

    ticket = nil
    if company_file_path.nil?
      QBWC.logger.info "Authentication of user '#{username}' failed."
      company_file_path = AUTHENTICATE_NOT_VALID_USER
    elsif !QBWC.pending_jobs(username).present?
      QBWC.logger.info "Authentication of user '#{username}' succeeded, but no jobs pending for '#{username}'."
      company_file_path = AUTHENTICATE_NO_WORK
    else
      QBWC.logger.info "Authentication of user '#{username}' succeeded, jobs are pending for '#{username}'."
      ticket = QBWC.storage_module::Session.new(username, username).ticket
      QBWC.session_initializer.call(get_session(ticket)) unless QBWC.session_initializer.nil?
    end
    render :soap => {"tns:authenticateResult" => {"tns:string" => [ticket || '', company_file_path]}}
  end
```

Basically anything that accesses pending_jobs has been passed the username field instead of company_file_path, which in my case ensures that the job is linked to a unique company instead of a field that could potentially be the same for multiple companies.

I've also added several database indexes to ensure scalable lookups:

```ruby
    add_index :qbwc_jobs, :name, unique: true
    add_index :qbwc_jobs, :company
```

When I create jobs, I do it like so:

```ruby
QBWC.add_job "fetch_vendors_for_#{username}", true, username, Integration::QbdWorkers::FetchWorker
```

Note that I use the username instead of the company_file_path, and I also need to encode it into the job's name to ensure it's unique, which seems redundant.

Some of my fixes seem to me like they'd benefit your use case too.  Other fixes of mine break your existing use cases.  If I had time, I'd try to implement more general fixes, and then issue a pull request.  As it is, I'll just list suggestions here on how to potentially incorporate my code into more general solutions for your gem.

## Storing and filtering company-unique values

My biggest issue was that the company_file_path isn't unique if you aren't working with a single set of company files.  I think the gem should allow users to define what to use as the unique value via a Proc.  You already use a Proc to define the authenticator and session_initializer code when configuring the gem.  It would be easy enough to add another one to retrieve a company-unique value.  Pass the session into the proc, and then the user can return whatever value he or she wants.  It could default to the company_file_path to stay consistent with your existing code.

This proc would then be used when determining what jobs are pending for a given session.  And the user would have to use that same value when adding jobs if he or she wanted a new job to apply to a particular company.

```ruby
c.company_unique_value = Proc.new{|session|
  session.username

  # or

  lookup_company_file_path_for(session.username)

  # or

  Company.find_by(username: session.username).id

}
```
## Database Indexes

This is obviously really important for anything that wants to be scalable past a hundred or so companies.

There needs to be an index on qbwc_jobs's company field, as I included above.  Also, in my opinion, the uniqueness constraint on name needs to also include the company column so that I don't have to redundantly encode the unique company id into the job name.  Actually, I think this is a bug fix for something that is likely plaguing your current use case too, you maybe just haven't run into it yet.

```ruby
add_index :qbwc_jobs, :company
add_index :qbwc_jobs, [:name, :company], unique: true
```

and 

```ruby
class QbwcJob < ActiveRecord::Base
    validates :name, :uniqueness => {:scope => :company}, :presence => true
end
```

There are likely database indexes which would be helpful on the qbwc_sessions table too, but I haven't examined that code yet to figure them out.

Anyway, hopefully this provides some food for thought.

**Comment by JasonBarnabe** [comment]
> If there are 5000 businesses connected to QBWC, each which, say, have 3 CreateResource workers queued up, your solution would fetch (5000 x 3) jobs for each incoming QWBC action request and run each against the should_run? method in ruby to see whether it should be performed or not, no?

Why wouldn't you have one `CreateResource` job that determined what do for any given session? I've found it makes much more sense to have one job per type of action (e.g. "add invoice") and then perform logic in there to see what work needs to be done than to have one job per invoice or per company.

**Comment by bkroeker** [comment]
I guess I don't really understand how that would work.  How would you be able to specify the conditional query in QBWC::Worker#requests without creating multiple jobs?

What I'm doing right now is essentially:

```ruby
class Invoice < ActiveRecord::Base
  belongs_to :company
  on_create :persist_to_quickbooks

  def persist_to_quickbooks
    QBWC.add_job "create_invoice_for_#{company.id}", true, company.id, Integration::QbdWorkers::CreateResourceWorker, "{request hash for creating invoice in quickbooks}"
  end
end
```

How would you suggest I rewrite that?

**Comment by JasonBarnabe** [comment]
To be able to update the invoice, you will need to store the QuickBooks identifier somewhere. So add a `quickbooks_number` column; if that column is null, it's not in QuickBooks. Then, in your "add invoice" worker, `Invoice.where(quickbooks_number: nil, company_id: whatever)`.

**Comment by bkroeker** [comment]
How do I know what company to lookup?  As far as I can tell, no company-identifying values are passed into QBWC::Worker#requests.

**Comment by bkroeker** [comment]
Or are you referring to your earlier suggestion of modifying the gem to pass the session into QBWC::Worker#requests?

**Comment by JasonBarnabe** [comment]
Yes.

**Comment by bkroeker** [comment]
I see what you're saying.  I'll give it a try tomorrow and get back to you.

**Comment by JasonBarnabe** [comment]
Even without this issue, I don't find it a good idea to rely on the data in `qbwc_jobs` for any business purpose. What if the add fails? What if you accidentally clear the jobs? What about invoices created before you added QB integration? And in your example, what happens if two invoices are pending to be added? It's very difficult to query the data in `qbwc_jobs` to figure out the status of any invoice.

**Comment by bkroeker** [comment]
I had plans for each of those cases, but I understand what you're saying.

**Comment by bkroeker** [comment]
Hi Jason.  So after an epic code brawl that ended in bloody fisticuffs, I seem to have something in place that functions more or less as I want it to.  I'm pasting the latest iteration of changes I made to your gem below, and I hope you'll have a quick look and tell me if anything looks problematic from your perspective.

The main changes are:
- I'm passing the session into Worker#should_run? and Worker#requests, like you suggested.
- I'm also passing in the data object, since I make use of it.
- I added a proc that gets called when the session completes successfully.
- I exposed the session's created_at time through the session object, so I can tell when the session began processing.

These changes allow me to:
- conditionally decide with greater control when a worker should run, and what its requests should be
- keep track of when sessions were last successfully run, so that future requests can, for example, only fetch entities from QB which were updated since my code last ran, thus reducing the amount of data passed through the wire, and the amount of work I have to do processing it.

```ruby
module QBWC
  # Added hook for proc to be called when session was completed successfully:
  mattr_accessor :session_complete_success
  @@session_complete_success = nil

  # Change: accept and pass on session parameter
  def self.pending_jobs(company, session)
    js = jobs
    QBWC.logger.info "#{js.length} jobs exist, checking for pending jobs for company '#{company}'."
    storage_module::Job.sort_in_time_order(js.select {|job| job.company == company && job.pending?(session)})
  end
end

class QBWC::Session
  def next_request
    if current_job.nil? || error_and_stop_requested?
      self.progress = 100
      complete_with_success unless response_is_error? # line added: successfully completed; call callback
      return nil
    end
    until (request = current_job.next_request(self)) do # change: added parameter to next_request
      pending_jobs.shift
      reset(true) or break
    end
    jobs_completed = @initial_job_count - pending_jobs.length
    self.progress = ((jobs_completed.to_f  / @initial_job_count.to_f ) * 100).to_i
    complete_with_success if finished? # line added: successfully completed; call callback
    request
  end

  # New method: Call the session_complete_success callback proc
  def complete_with_success
    QBWC.session_complete_success.call(self) if QBWC.session_complete_success
  end

  # New method: return the datetime the session was started
  def began_at
    @session.created_at
  end

  private
    def pending_jobs
      @pending_jobs ||= QBWC.pending_jobs(@company, self) # change: added parameter to pending_jobs
    end
end

class QBWC::Job
  # Change: accept and pass on session parameter
  def pending?(session)
    if !enabled?
      QBWC.logger.info "Job '#{name}' not enabled."
      return false
    end
    sr = worker.should_run?(self, session, @data)
    QBWC.logger.info "Job '#{name}' should_run?: #{sr}."
    return sr
  end

  # Change: accept and pass on session parameter
  def next_request(session)
    # Generate and save the requests to run when starting the job.
    if (requests.nil? || requests.empty?) && ! self.requests_provided_when_job_added
      r = worker.requests(self, session, @data) # Change: added parameters for session and data
      r = [r] unless r.nil? || r.is_a?(Array)
      self.requests = r
    end

    QBWC.logger.info("Requests available are '#{requests}'.") if QBWC.log_requests_and_responses
    ri = request_index
    QBWC.logger.info("Request index is '#{ri}'.")
    return nil if ri.nil? || requests.nil? || ri >= requests.length
    nr = requests[ri]
    QBWC.logger.info("Next request is '#{nr}'.") if QBWC.log_requests_and_responses
    return QBWC::Request.new(nr)
  end
end

class QBWC::Worker
  # Change: Added parameters for session and data
  def requests(job, session, data)
    []
  end

  # Change: Added parameters for session and data
  def should_run?(job, session, data)
    true
  end
end

module QBWC::Controller
  # Change: Reorganized code so it fetches the session and passes it into the pending_jobs call
  def authenticate
    username = params[:strUserName]
    password = params[:strPassword]
    if !QBWC.authenticator.nil?
      company_file_path = QBWC.authenticator.call(username, password)
    elsif username == QBWC.username && password == QBWC.password
      company_file_path = QBWC.company_file_path
    else
      company_file_path = nil
    end

    ticket = nil
    if company_file_path.nil?
      QBWC.logger.info "Authentication of user '#{username}' failed."
      company_file_path = AUTHENTICATE_NOT_VALID_USER
    else
      ticket = QBWC.storage_module::Session.new(username, company_file_path).ticket
      session = get_session(ticket)

      if !QBWC.pending_jobs(company_file_path, session).present?
        QBWC.logger.info "Authentication of user '#{username}' succeeded, but no jobs pending for '#{company_file_path}'."
        company_file_path = AUTHENTICATE_NO_WORK
      else
        QBWC.logger.info "Authentication of user '#{username}' succeeded, jobs are pending for '#{company_file_path}'."
      
        QBWC.session_initializer.call(session) unless QBWC.session_initializer.nil?
      end
    end
    render :soap => {"tns:authenticateResult" => {"tns:string" => [ticket || '', company_file_path]}}
  end
end
```

Thanks!

**Comment by JasonBarnabe** [comment]
All these things sound good. Put them in a pull request and I'll take a look at it. Thanks!

**Comment by rchekaluk** [comment]
I haven't fully absorbed this discussion, but I'm wondering out loud if there's any value in making session an optional argument for backwards compatibility sake?

**Comment by bkroeker** [comment]
Unfortunately, Ruby doesn't allow for multiple definitions of the same methods using different parameters.  In Java you can do that, like:

```java
public class QBWCWorker {
  public boolean requests(Job job, Session session, Data data) {
    // ...
  }
  
  public boolean requests(Job job) {
    // ...
  }
}
```

But you can't do that in Ruby, as the second definition would override the first.

Also, there are other non-backwards-compatible changes, such as schema changes.

**Comment by JasonBarnabe** [comment]
You could potentially check the arity of the method in the worker, but I'm not sure we want to go down that road... I had thought of making it so that the worker methods would receive a hash instead of individual arguments, but I'm not sure that that is better either.
