### ISSUE TITLE
Support for multiple concurrent Sessions

### ISSUE THREAD

**Issue by ratbeard** [qbwc/qbwc#81]
Hello, thank you for this gem, its been a huge help to me.  I am trying to use it in a way similar to #79.  Many users will connect to our site to upload their company's financial data, and then we generate a report.  I've been reading through the code to learn how to best support multiple users, and I think I'm seeing a potential issue for us:

If one user is uploading their data and another user begins an upload, the first user's Session will get clobbered due to Session storing a single `@@session` in memory at any given time [1].  When the 2nd user authenticates, it creates a new session [2], which overwrites the 1st user's session in mid-upload [3].

I know you originally wrote this targeting the use case of a few users within a company where this issue would probably not come up.  Just wanted to confirm that this is the current behavior and I'm not missing something.  I'll be doing some thinking on how I can fix this if it is the case, perhaps storing Session in the database.

Thanks! :swimmer: 

[1]: https://github.com/qbwc/qbwc/blob/master/lib/qbwc/session.rb#L6-L10
[2]: https://github.com/qbwc/qbwc/blob/master/lib/qbwc/controller.rb#L123
[3]: https://github.com/qbwc/qbwc/blob/master/lib/qbwc/session.rb#L23

**Comment by ratbeard** [comment]
Hmm, It looks like I overlooked `class QBWC::ActiveRecord::Session < QBWC::Session`, which does persist session to the database!

**Comment by JasonBarnabe** [comment]
If you see any problems when using this, feel free to report. This is not a use case I've personally tried.
