### ISSUE TITLE
How to create hash with repeated elements?

### ISSUE THREAD

**Issue by bkroeker** [qbwc/qbwc#82]
Hi there.  I'm trying to upload new resources to Quickbooks Desktop using the following kind of request:

```ruby
# eg.
class UploadPurchaseOrderWorker < QBWC::Worker
  def requests(job, session, data)
    {:purchase_order_add_rq=>[{
      :purchase_order_add=>{:vendor_ref=>{:list_id=>"80000007-1439054250"}, ...}
    }]}
  end
end
```

Now the problem is that QB accepts repeated XML elements:
```xml
<PurchaseOrderAddRq>
  <PurchaseOrderAdd>
    <VendorRef> 
      <ListID >IDTYPE</ListID> 
    </VendorRef>
    ...
    <PurchaseOrderLineAdd>...</PurchaseOrderLineAdd>
    <PurchaseOrderLineAdd>...</PurchaseOrderLineAdd>
    <PurchaseOrderLineAdd>...</PurchaseOrderLineAdd>
    ...
  </PurchaseOrderAdd>
</PurchaseOrderAddRq>
```

How can I create a ruby hash for QBWC::Worker#requests such that it will generate multiple PurchaseOrderLineAdd elements in the XML it sends to QB?

Thanks.

**Comment by JasonBarnabe** [comment]
Should work with a key of `:purchase_order_line_add` with a value of an Array of Hashes. I haven't done this with purchase orders, but I have with invoices and receipts.

**Comment by bkroeker** [comment]
That works splendidly.  Thanks!
