### ISSUE TITLE
How to associate newly created QB resources with ruby app resources

### ISSUE THREAD

**Issue by bkroeker** [qbwc/qbwc#83]
Hi again.  This might be more of a web connector question, but it's got me stumped.  Can you offer me some advice again, please?

I've got some ruby resources, let's say Ruby Invoices A, B, and C.  Ruby Invoice A is updated, and B & C are new.  I create a QBWC job to create/update the equivalent invoices in QB.  (Note: these invoices would be programmatically determined, but I'm explicitly writing them out here for clarity.)

```ruby
class UploadWorker < QBWC::Worker
  def requests(job, session, data)
    [
      {invoice_mod_rq: {invoice_mod: [
        ruby_invoice_a.qb_hash # eg. {txn_id: "blah-blah-a", ...}
      ]}},
      {invoice_add_rq: {invoice_add: [
        ruby_invoice_b.qb_hash,
        ruby_invoice_c.qb_hash
      ]}}
    ]
  end
  
  def handle_response(r, session, job, request, data)
    r[:invoice_ret].each do |qb_invoice_result|
      # associate qb_invoice_result with corresponding ruby invoice
    end
  end
end
```

My question is how to implement that comment in the handle_response method.  Ideally I'd like to say:
* Ruby Invoice B is associated with the QB Invoice whose txn_id is "blah-blah-b"
* Ruby Invoice C is associated with the QB Invoice whose txn_id is "blah-blah-c"

My first thought was to use the "ExternalGUID" field, which seems designed for this sort of thing.  I said:
* Ruby Invoice B has a GUID of "ABEFECCA-E4B9-446A-975C-1A4A67E66093"
* Ruby Invoice C has a GUID of "C45EEFBD-F087-442B-9C70-4CFCE4564661"

I then passed these GUIDs into the request hash, expecting that the responses from QB would return the GUIDs and allow me to say:
* Ruby Invoice with GUID "ABEFECCA-E4B9-446A-975C-1A4A67E66093" has txn_id of "blah-blah-b"
* Ruby Invoice with GUID "C45EEFBD-F087-442B-9C70-4CFCE4564661" has txn_id of "blah-blah-c"

However, it seems that despite its claims, the QB connector can't parse valid GUIDs.

```
There was an error when converting the GUID value "ABEFECCA-E4B9-446A-975C-1A4A67E66093" in the field "ExternalGUID".
```

Is there a recommended alternative solution?

Thanks!

**Comment by bkroeker** [comment]
What I ended up doing is relying on the seemingly flimsy assumption that results are returned in the same order and number that they were requested, and recreating the exact same query to determine the resources in both the requests and handle_response methods, which necessitated relying on features in my pull request from a month ago.

Here's a much simplified version of what I ended up with:

```ruby
# Store timestamps of when sessions begin and complete:
QBWC.configure do |c|
  c.session_initializer = Proc.new { |session|
    connection = QuickbooksDesktop::Connection.find_by username: session.user
    connection.update_attributes run_started_at: session.began_at
  }

  c.session_complete_success = Proc.new { |session| 
    connection = QuickbooksDesktop::Connection.find_by username: session.user
    connection.update_attributes prev_ran_at: connection.last_ran_at, last_ran_at: connection.run_started_at 
  }
end

class User
  has_one :connection
  has_many :invoices
end

class Invoice
  belongs_to :user
  
  scope :unassociated,   lambda { where(arel_table[:qb_key].eq(nil)) }
  scope :associated,     lambda { where(arel_table[:qb_key].not_eq(nil)) }
  scope :updated_after,  lambda { |time| where(arel_table[:updated_at].gteq(time)) }
  scope :updated_before, lambda { |time| where(arel_table[:updated_at].lt(time)) }
end

class UploadInvoicesWorker < QBWC::Worker
  def requests(job, session, data)
    connection = QuickbooksDesktop::Connection.find_by username: session.user
    
    # Find updated invoices and split them into add and mod categories.
    updated_invoices = connection.user.invoices.updated_after(connection.prev_ran_at).updated_before(connection.run_started_at)
    invoices_to_add = updated_invoices.unassociated
    invoices_to_mod = updated_invoices.associated
    
    [
      {invoice_mod_rq: {invoice_mod: [
        invoices_to_mod.map(&:qb_hash) # { txn_id: invoice.qb_key, edit_sequence: invoice.qb_edit_sequence, ...}
      ]}}
      {invoice_add_rq: {invoice_add: [
        invoices_to_add.map(&:qb_hash)
      ]}}
    ]
  end
  
  def handle_response(r, session, job, request, data)
    connection = QuickbooksDesktop::Connection.find_by username: session.user
    returned_invoices = r[:invoice_ret]
    
    if request.keys.first.to_s =~ /_add_/
      # If this is from the add request, update all local invoices with QB Keys and Edit Sequences.
      invoices_to_add = connection.user.invoices.updated_after(connection.prev_ran_at).updated_before(connection.run_started_at).unassociated
      
      raise "# of returned invoices != # of requested invoices" unless invoices_to_add.size == returned_invoices.size
      
      invoices_to_add.zip(returned_invoices).each do |my_invoice, qb_invoice|
        # Kludge: Using Invoice.update_all prevents updated_at timestamps from bumping, and thus from being flagged for update on the next QBWC session
        Invoice.where(id: my_invoice.id).update_all qb_key: qb_invoice[:txn_id], qb_edit_sequence: qb_invoice[:edit_sequence]
      end
    else
      # If this is from the mod request, update all local invoices' Edit Sequences.
      returned_invoices.each do |qb_invoice|
        my_invoice = connection.user.invoices.find_by qb_key: qb_invoice[:txn_id]
        Invoice.where(id: my_invoice.id).update_all qb_edit_sequence: qb_invoice[:edit_sequence]
      end
    end
  end
end
```

So it's not the prettiest solution, but it seems functional-ish.  I'll close the ticket but am open to better suggestions.

**Comment by JasonBarnabe** [comment]
I'm not sure what the problem with setting the GUID is. Maybe it wants brackets, or no dashes, or lowercase. I couldn't find a reference online saying what it's expecting.

I don't know why that would be necessary, though. Is your `ref_number` not unique?

**Comment by bkroeker** [comment]
From the documentation: 
```
A GUIDTYPE value takes the form {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}, where X is a hexadecimal digit. For example: {6B063959-81B0-4622-85D6-F548C8CCB517}
```

I can't see how my GUID is any different than that.  Unless it's expecting the curly brackets?

And I didn't want to rely on ref_number since that's a user-controlled field that they can change.  Plus, it doesn't apply to all resource types that I want to do this for, like BillPaymentChecks.

**Comment by JasonBarnabe** [comment]
In what I do, I rely on storing the QuickBooks `txn_id` in my DB rather than storing anything in QuickBooks. Not sure if this is feasible for your case.

**Comment by bkroeker** [comment]
What I'm doing is storing data in both places and trying to keep them in sync.  So I do store the txn_id in my DB; the problem is how to get it when a resource (eg. invoice) is created in my app and then I sync it up to QB.  So I start with an invoice in my app, I create the equivalent invoice in QB, and then I need to store the returned txn_id in my DB so I can use it to issue further updates to the QB invoice.  However because of the nature of QBWC, when I tell QB to create multiple invoices at once, it's non-trivial to know which of my local invoices each received QB response is for.
