### ISSUE TITLE
ActiveRecord::SerializationTypeMismatch after migrating to new schema

### ISSUE THREAD

**Issue by rchekaluk** [qbwc/qbwc#87]
Following the draft migration instructions included in https://github.com/qbwc/qbwc/pull/86, yields this error for me when attempting to `QBWC.add_job`:
```
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a Fixnum. -- 0
```
I presume this is in reference to `request_index`.

cc @bkroeker

**Comment by JasonBarnabe** [comment]
What was the code that you ran?

**Comment by bkroeker** [comment]
This is because of the column type change in the database.

**Comment by bkroeker** [comment]
Oh yeah -- you even identified it as such, @rchekaluk.  Sorry, I missed that.

It should be resolved by clearing the table and recreating the jobs.

**Comment by rchekaluk** [comment]
So IMO we should tweak [draft migration instructions](https://github.com/rchekaluk/qbwc/commit/f02636cfbd6565bfd7434f48ba54d379f80399a2) to show the steps necessary to upgrade to this version and it's revised schema.

**Comment by rchekaluk** [comment]
Duplicate https://github.com/qbwc/qbwc/issues/85

**Comment by rchekaluk** [comment]
User error, neglected to run migrations for RAILS_ENV=test. I've updated the draft migration instructions accordingly.

**Comment by Rishka** [comment]
If anyone else runs into this issue, I solved it by just setting each job's request to nil after migrating. No need to recreate the jobs.
