### ISSUE TITLE
ArgumentError: Before process_action callback :_parse_soap_parameters has not been defined

### ISSUE THREAD

**Issue by DexterTheDragon** [qbwc/qbwc#92]
I was attempting to run my application on the Rails 5.0.0.rc1 today and got the error

```
ArgumentError: Before process_action callback :_parse_soap_parameters has not been defined
```

It is being triggered by [`lib/qbwc/controller.rb:13`](https://github.com/qbwc/qbwc/blob/master/lib/qbwc/controller.rb#L13). That line is 

``` ruby
skip_before_filter :_parse_soap_parameters, :_authenticate_wsse, :_map_soap_parameters, :only => :qwc
```

Looking into wash_out it looks like the _parse_soap_parameters filter was removed in this commit https://github.com/inossidabile/wash_out/commit/491f2f4643db08ef7b3704184cc212cbe91dda8f back in 2013.

I'm guessing that Rails 4 is just ignoring the fact that it doesn't exist but Rails 5 seems to be stricter.

**Comment by JasonBarnabe** [comment]
Maybe it was caused by washout getting updated too?

Try the latest master to see if it works.

**Comment by DexterTheDragon** [comment]
It was using wash_out 0.10.0 on Rails 4 and Rails 5 rc1.

Tested your lasted changes and they appear to work.

**Comment by faralbrt** [comment]
I am having the same issue

**Comment by lostapathy** [comment]
Working from master does resolve this issue with Rails 5.

What would we need to get done in order to tag a new gem version to include this so people don't need to run off master to avoid this bug?

**Comment by faralbrt** [comment]
I wouldn't know...sorry

Thanks anyway

**Comment by calebhaye** [comment]
First off, it working off of master is much better than nothing.

Secondly, I saw something similar in devise, I wonder if it's related?  In that post, they mention that this error has nothing to do with any gems...it is due to changes in the skip_xxx_action in rails 5, and that we need to add `, raise: false` to the `skip_before_action` line, i.e. 
```ruby
skip_before_filter :_parse_soap_parameters, :_authenticate_wsse, :_map_soap_parameters, :only => :qwc, raise: false
```
Has anyone tried that?

**Comment by pjrebsch** [comment]
Hey @calebhaye, I tried your suggestion and indeed it works for me.

**Comment by DexterTheDragon** [comment]
@JasonBarnabe any chance you could release a new gem version with the Rails 5 fixes that are on master?
